import yaml
import os

def generate_model():
    base_dir = os.path.dirname(os.path.dirname(__file__))
    rules_path = os.path.join(base_dir, "rules.yml")
    model_path = os.path.join(base_dir, "dbt_project", "models", "intermediate", "int_lead_scoring.sql")

    if not os.path.exists(rules_path):
        print(f"[Generator] {rules_path} not found. Skipping generation.")
        return

    with open(rules_path, "r") as f:
        data = yaml.safe_load(f)

    rules_sql = ""
    for rule in data.get("scoring_rules", []):
        condition = rule["sql_condition"]
        points = rule["points"]
        desc = rule.get("description", "")
        rules_sql += f"        -- {desc}\n"
        rules_sql += f"        + case when {condition} then {points} else 0 end\n"

    sql_content = f"""-- Auto-generated by scripts/generate_scoring_model.py
with staged_leads as (
    select * from {{{{ ref('stg_leads') }}}}
),

scoring as (
    select
        *,
        -- Base score
        0 
{rules_sql}        as calculated_score
    from staged_leads
)

select * from scoring
"""

    with open(model_path, "w") as f:
        f.write(sql_content)
    print("[Scoring Generator] Successfully generated int_lead_scoring.sql from rules.yml")

if __name__ == "__main__":
    generate_model()
